config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  delete 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'dashboards#index'
  resources :users do
    collection do
      post :upload_file
      get :assign_desc
    end
  end

	namespace :admin do
    resources :assignments do
    	member do
	      post :sent_to_users
        get :download_as_excel
      end

    end
    resources :dashboards, only: [:index]
    resources :users, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :cas_authenticatable

  enum role: [:user, :admin]

  has_many :assignment_users, dependent: :destroy
  has_many :assignments, through: :assignment_users


  def cas_extra_attributes=(extra_attributes)
    extra_attributes.each do |name, value|
    case name.to_sym
      when :commonName
        self.name = value
      when :mailAlias
        self.email = value
      when :uid
        self.uid = value
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    # Uses enum functionality to filter out admins
    @users = User.user
		@users = @users.sort_by{|x| x[:name]}
		
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    flash[:notice] = "User successfully deleted."
    redirect_to admin_users_path
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  protected
    def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
    end

    def configure_account_update_params
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :role])
    end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  protected
    def after_sign_in_path_for(_resource)
      if current_user.admin?
        admin_dashboards_path
      else
        root_path
      end
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:type] == 'lab'
    $lab = 1
      @assignments = Assignment.lab.where(sent_to_users: true)
			@assignments = @assignments.sort_by{|x| x[:title]}
    else
      $lab = 0
      @assignments = Assignment.assignment.where(sent_to_users: true)
			@assignments = @assignments.sort_by{|x| x[:title]}
    end
  end

  def upload_file
    user_assignment = current_user.assignment_users.find_by(assignment_id: params[:assignment_user][:assignment_id])    
    if user_assignment.present?
      user_assignment.destroy
    end 
    @assignment_user = current_user.assignment_users.new(assignment_params)
    if @assignment_user.save
      save_file_separate_folder
      run_script(@assignment_user)
      if @timeout
        flash[:alert] = 'Your assignment took too long and was terminated.  Check for an infinite loop and resubmit.'
      else
        flash[:notice] = 'File created successfully'
      end
    elsif @assignment_user.file.blob.byte_size > 1000
      flash[:alert] = 'Assignment size should be less than or equal to 10kb'
    else
      flash[:alert] = 'Assignment not created successfully'
    end   
    if $lab == 1
      redirect_to users_path(type: 'lab') 
    else
      redirect_to users_path 
    end  
  end

  def save_file_separate_folder
    assignment = Assignment.find_by(id: params[:assignment_user][:assignment_id])
    uploaded_io = params[:assignment_user][:file]
    dest_folder = "#{Rails.root}/temp/#{assignment.title}"
    FileUtils.mkdir_p(dest_folder) unless File.directory?(dest_folder)
    filename = ActiveStorage::Blob.service.path_for(assignment.assignment_users.first.file.blob.key)
    FileUtils.cp(filename, "#{dest_folder}/#{current_user.email}_#{uploaded_io.original_filename}")
  end

  def run_script(assignment_user)
    assignment         = Assignment.find_by(id: params[:assignment_user][:assignment_id])
		uploaded_io = params[:assignment_user][:file]
    argument           = assignment.argument.present? ? assignment.argument : " "
    command            = assignment.command
    student_assignment = ActiveStorage::Blob.service.path_for(assignment_user.file.blob.key)
    grading_script     = ActiveStorage::Blob.service.path_for(assignment.grading_script_file.blob.key)
    FileUtils.cd("#{Rails.root}/temp/#{assignment.title}")
    cmd = "#{command} #{grading_script} #{student_assignment} \'#{uploaded_io.original_filename}\'"
    begin
      stdout, stderr, status = Timeout::timeout(15) do
         Open3.capture3(cmd)
      end
      @timeout = false
    rescue Timeout::Error => e
      @timeout = true
    end

    destination = "#{Rails.root}/student_submissions/#{assignment.title}"
    FileUtils.mkdir_p(destination) unless File.directory?(destination)

    if @timeout
      assignment_user.grade = -1.0
    else
      assignment_user.grade = stdout.to_f
      dest_folder = "#{Rails.root}/temp/#{assignment.title}/#{current_user.email}_#{assignment.title}_rubric"
      File.open(dest_folder, "w") { |file| file.puts "#{stderr}"}
      assignment_user.rubric.attach(
        io: File.open(dest_folder),
        filename: "#{current_user.email}_#{assignment.title}_rubric.txt"
      )
      filename = ActiveStorage::Blob.service.path_for(assignment_user.rubric.blob.key)
      FileUtils.cp(filename, "#{destination}/#{current_user.email}_#{assignment.title}_rubric.txt")
    end

    assignment_user.save
    uploaded_file = params[:assignment_user][:file]

    filename = ActiveStorage::Blob.service.path_for(assignment.assignment_users.first.file.blob.key)
    FileUtils.cp(filename, "#{destination}/#{current_user.email}_#{uploaded_file.original_filename}")

    return @timeout
  end

  def assign_desc
    @assignment = Assignment.find(params[:assignment])
  end

  private

    def assignment_params 
      params.require(:assignment_user).permit(:assignment_id, :file)
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_assignment(assignment)
    assignment.assignment_users.find_by(user_id: current_user.id)&.file
  end

  def user_rubric(assignment)
    assignment.assignment_users.find_by(user_id: current_user.id)&.rubric
  end

  def user_grade(assignment)
    assignment.assignment_users.find_by(user_id: current_user.id)&.grade
  end

  def active_class?(path)
    if request.fullpath == path
      return 'nav-link active'
    else
      return 'nav-link'
    end
  end
end

app/views/users/assign_desc.html.erb
<div class="container">
	<%= render 'shared/header' %>
	<div class="row mt-5">
		<h2>Assignment Details</h2>
	</div>
	<div class="row mt-5">
		<table class="table table-bordered table-striped table-hover">
      <tr>
        <th class='text-center'>Title</th>
        <td class='text-center'><%= @assignment.title.humanize %></td>
      </tr>
      <tr>
        <th class='text-center'>Type</th>
        <td class='text-center'><%= @assignment.assignment_type.humanize %></td>
      </tr>
      <tr>
        <th class='text-center'>Description</th>
        <td class='text-center'><%= @assignment.description.present? ? @assignment.description.html_safe : "N/A" %></td>
      </tr>
      <tr>
        <th class='text-center'>Due Date</th>
        <td class='text-center'><%= @assignment.due_date.strftime('%a %d %b %Y by %l:%M %p') %></td>
      </tr>
      <tr>
      	<th class='text-center'>Rubric</th>
      	<td class='text-center'>
          <% if user_rubric(@assignment)&.attached? %>
            <%= link_to user_rubric(@assignment)&.blob.filename, rails_blob_path(@assignment.assignment_users.first.rubric, disposition: "attachment") %>
          <% else %>
            Not Available yet
          <% end %>
        </td>
      </tr>
      <tr>
      	<th class='text-center'>Grade</th>
        <td class='text-center'><%= user_grade(@assignment).present? ? user_grade(@assignment) : 'Not Available yet' %></td>
      </tr>
      <tr>
      	<th class='text-center'>Uploaded File</th>
        <td class='text-center'>
          <% if user_assignment(@assignment)&.attached? %>
            <%= link_to user_assignment(@assignment)&.blob.filename, rails_blob_path(@assignment.assignment_users.first.file, disposition: "attachment") %>
          <% else %>
            Not Uploaded yet
          <% end %>
        </td>
      </tr>
      <tr>
      	<th class='text-center'>Upload Assignment</th>
        <td class='text-center'>
          <%= form_for :assignment_user, local: true, url: upload_file_users_path, method: :post, html: { class: 'form-horizontal', 'data-parsley-validate': '' } do |f| %>
            <div class="input-group">
            	<div class='offset-4'>
	              <%= f.hidden_field :assignment_id, value: @assignment.id %>
	              <%= f.file_field :file, required: true %>
	              <span class="input-group-btn">
	                <%= f.submit 'Upload', class: 'btn btn-primary btn-group' %>
	              </span>
            	<div>
            </div>
          <% end %>
        </td>
      </tr>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <%= render 'shared/header' %>

  <div class="row mt-5">
    <div class="col-lg-12">
      <h2 class= 'float-left'> Assignments!</h2>
    </div>
  </div>
  <div class="row">
    <div class="offset-5 mt-5">
      <ul class="nav nav-pills" role="tablist">
        <li class="nav-item">
          <%= link_to 'Homework', users_path(type: 'assignment'), class: active_class?('/users?type=assignment') %>
        </li>
        <li class="nav-item">
          <%= link_to 'Labs', users_path(type: 'lab'), class: active_class?('/users?type=lab')  %>
        </li>
      </ul>
    </div>
  </div>

  <div class="row mt-5">
    <% if @assignments.present? %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th class='text-center'>Title</th>
            <th class='text-center'>Description</th>
            <th class='text-center'>Due Date</th>
            <th class='text-center'>Rubric</th>
            <th class='text-center'>Grade</th>
            <th class='text-center'>Uploaded File</th>
            <th class='text-center'>Upload Assignment</th>    
          </tr>
        </thead>
        <% @assignments.each do |assignment| %>
          <tbody>
            <tr>
              <td class='text-center'><%= link_to assignment.title.humanize, assign_desc_users_path(assignment: assignment) %></td>
              <td class='text-center'><%= assignment.description.present? ? assignment.description[3..25] : "N/A" %></td>
              <td class='text-center'><%= assignment.due_date.strftime('%a, %-m/%d %l:%M %p') %></td>
              <td class='text-center'>
                <% if user_rubric(assignment)&.attached? %>
                  <%= link_to user_rubric(assignment)&.blob.filename, rails_blob_path(user_rubric(assignment), disposition: "attachment") %>
                <% else %>
                  Not Available yet
                <% end %>
              </td>
              <td class='text-center'><%= user_grade(assignment).present? ? user_grade(assignment) : 'Not Available yet' %></td>
              <td class='text-center'>
                <% if user_assignment(assignment)&.attached? %>
                  <%= link_to user_assignment(assignment)&.blob.filename, rails_blob_path(user_assignment(assignment), disposition: "attachment") %>
                <% else %>
                  Not Uploaded yet
                <% end %>
              </td>
              <td class='text-center'>
                <%= form_for :assignment_user, local: true, url: upload_file_users_path, method: :post, html: { class: 'form-horizontal', 'data-parsley-validate': '' } do |f| %>
                  <div class="input-group">
                    <%= f.hidden_field :assignment_id, value: assignment.id %>
                    <%= f.file_field :file, required: true, class: 'form-control' %>
                    <span class="input-group-btn">
                      <%= f.submit 'Upload', class: 'btn btn-primary btn-group' %>
                    </span>
                  </div>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    <% else %>
      <h4 class='text-center'>You have not been assigned any assignment yet.</h4>
    <% end %>
  </div>
</div>