config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  delete 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root 'dashboards#index'
  resources :users do
    collection do
      post :upload_file
      get :assign_desc
    end
  end

	namespace :admin do
    resources :assignments do
    	member do
	      post :sent_to_users
        get :download_as_excel
      end

    end
    resources :dashboards, only: [:index]
    resources :users, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<header class="header ">
  <div class="main_nav_container">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <% if current_user.admin? %>
            <%= link_to "Dashboard", admin_dashboards_path, class: 'btn btn-warning' %>
            <%= link_to "Assignments", admin_assignments_path, class: 'btn btn-success' %>
            <%= link_to "Users", admin_users_path, class: 'btn btn-info' %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to "Dashboard", root_path, class: 'btn btn-warning' %>
            <%= link_to "Assignments", users_path(type: 'assignment'), class: 'btn btn-success' %>
            <%= link_to "Sign Out",destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>